#!/bin/bash

echo ====================Script Started=================== >> log


python extract.py
python transform.py
python load.py
echo ======================Script Ended==================== >> log

echo
