#!/bin/bash

echo ====================Script Started=================== >> log

podman start nasa-postgres >>log 2>&1
python extract.py
python transform.py
python load.py
echo ======================Script Ended==================== >> log
podman stop nasa-postgres
echo
